### PR TITLE
Webserver tests

### PR DESCRIPTION
**Pull request by yanzunh**

### CODE REVIEW

**Comment by yanzunh** [comment]
finally passed the integration test lol

**Comment by echen94** [comment]
nice! I think the two lines in travis script helped :)

**Comment by echen94** [comment]
feel free to merge and we can test webserver file, reply file, and the integration test again after merging

**Comment by yanzunh** [comment]
Yeah! Also for future reference remember to remove the .o files and other binaries before merging to the master branch~~~

**Comment by echen94** [comment]
will do! will try to make clean before merging next time!

**Pull request merged**
